spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minto_membership_db
    username: postgres
    password: Admin@4321
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 191549397334-j1f6m6edr8qvem9pgmtltf73ngv5dit2.apps.googleusercontent.com
            client-secret: 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
          github:
            client-id: Ov23liEm9J5KObCgna6x
            client-secret: b37f70395c345449825952b8a37fa8b138060225
          facebook:
            client-id: 3781906558696522
            client-secret: ce59ff64ad618cfd39a5a186e3b06a79

application:
  security:
    jwt:
      secret-key: HZbVR3rlJ3E4BWKDoN1O7huUelOsfs5R0WbtGdnGpvOdMTs4rwJK0L0+WLv7RNq0
      expiration: 1200000 # 20 min (a day = 86400000)
      refresh-token:
        expiration: 21600000 # 6 hrs (7 days = 604800000)

frontend:
  url: http://localhost:3000